"use client";
import { createContext, useContext, useState, ReactNode } from "react";

// 1. Define available languages
export type Language = "en" | "fr";

// 2. Define the dictionary of words
const translations = {
        // ...existing code...
    en: {
        // Dashboard Site Info keys
        "dashboard.siteinfo.title": "Edit Site Info",
        "dashboard.siteinfo.homeTitle": "Homepage Title",
        "dashboard.siteinfo.homeTitleHelp": "This is the <Full Stack Developer & DevOps Developer/> text. Styling will remain unchanged.",
        "dashboard.siteinfo.homeStack": "Homepage Stack/Tech List",
        "dashboard.siteinfo.homeStackHelp": "This is the tech stack text (e.g. Next.js • Kubernetes • ...). Styling will remain unchanged.",
        "dashboard.siteinfo.homeDescription": "Homepage Description",
        "dashboard.siteinfo.homeDescriptionHelp": "This is the subtitle text under your name. Styling will remain unchanged.",
        "dashboard.siteinfo.contactEmail": "Contact Email",
        "dashboard.siteinfo.helpInfo": "What I Can Help With",
        "dashboard.siteinfo.directEmail": "Direct Email (for Send Message section)",
                "admin.experience.editTitle": "Edit Experience",
                "admin.experience.editSaveButton": "Save Changes",
                "admin.experience.editCancelButton": "Cancel",
                "admin.experience.editButton": "Edit",
            // Admin Dashboard Quick Actions
            "admin.dashboard.quickActions": "Quick Actions",
            "admin.dashboard.viewProjects": "View Projects",
            "admin.dashboard.manageProjects": "Manage your portfolio projects",
        // Public Projects page keys
        "projects.title": "Projects",
        "projects.intro": "Explore my portfolio of innovative applications and infrastructure solutions.",
        "projects.tagline": "Modern Tech • Scalable Architecture • Production Ready",
        "projects.comingSoon": "Coming Soon",
        "projects.empty": "Exciting projects are in development. Check back soon to see my latest work!",
        // Public Skills page keys
        "skills.title": "Skills & Expertise",
        "skills.intro": "A comprehensive overview of my technical abilities and professional toolset.",
        "skills.empty": "No skills added yet. Check back soon!",
        "skills.proficiencyLabel": "Proficiency",
        // Public Experience page keys
        "experience.title": "Work Experience",
        "experience.intro": "My professional journey and career milestones.",
        "experience.empty": "No experience added yet. Check back soon!",
        // Public Education page keys
        "education.title": "Education",
        "education.intro": "Academic qualifications and certifications.",
        "education.empty": "No education listed yet. Check back soon!",
        // CV page keys
        // Public Testimonials page keys
        // Public Hobbies page keys
        "hobbies.title": "Hobbies & Interests",
        "hobbies.intro": "What I enjoy doing when I'm not coding.",
        "hobbies.empty": "No hobbies added yet.",
        "hobbies.sectionTitle": "Hobbies",
        "testimonials.title": "Testimonials",
        "testimonials.intro": "Read authentic feedback from clients and collaborators.",
        "testimonials.empty": "No testimonials yet.",
        "testimonials.emptyDesc": "Share your experience above!",
        "testimonials.button": "Share Your Experience",
        "testimonials.loading": "Loading testimonials...",
        "testimonials.error": "Failed to load testimonials.",
        "testimonials.rating": "Rating",
        "testimonials.date": "Date",
        "testimonials.author": "Your Name",
        "testimonials.textLabel": "Your Testimonial",
        "testimonials.textPlaceholder": "Share your experience working with me...",
        "testimonials.submitButton": "Submit Testimonial",
        "testimonials.submitting": "Submitting...",
        "testimonials.cancel": "Cancel",
        "cv.title": "Resume",
        "cv.intro": "Download or view my latest CV below.",
        "cv.button": "View / Download CV",
        "cv.preview": "CV Preview",
        // Contact page keys
        "contact.title": "Contact",
        "contact.intro": "Have a project in mind? Let's discuss how we can work together to bring your ideas to life.",
        "contact.collabTagline": "Collaboration • Innovation • Results",
        "contact.connectTitle": "Let's Connect",
        "contact.emailTitle": "Email",
        "contact.locationTitle": "Location",
        "contact.locationDesc": "Available for remote work worldwide",
        "contact.responseTitle": "Response Time",
        "contact.responseDesc": "Usually within 24 hours",
        "contact.helpTitle": "What I Can Help With",
        "contact.helpWeb": "Full-stack web application development",
        "contact.helpCloud": "Cloud infrastructure setup and optimization",
        "contact.helpK8s": "Kubernetes deployment and DevOps consulting",
        "contact.helpArch": "Technical architecture and system design",
        // Admin Messages keys
        "admin.messages.title": "Messages",
        "admin.messages.subtitle": "View and manage contact form messages",
        "admin.messages.cta": "Stay connected with your audience",
        "admin.messages.sectionTitle": "Inbox",
        "admin.messages.deleteButton": "Delete",
        "admin.messages.confirmDelete": "Are you sure you want to delete this message?",
        "admin.messages.empty": "No messages yet.",
        "admin.messages.emptyDesc": "Messages submitted through your contact form will appear here.",
        "admin.messages.registeredUser": "Registered User",
        "admin.messages.loading": "Loading messages...",
        "admin.messages.error": "Failed to load messages.",
        "admin.messages.email": "Email",
        "admin.messages.name": "Name",
        "admin.messages.date": "Date",
        "admin.messages.message": "Message",
        // Admin Skills keys
        "admin.skills.title": "Skills",
        "admin.skills.subtitle": "Add, edit, and organize your technical skills",
        "admin.skills.addTitle": "Add New Skill",
        "admin.skills.nameLabel": "Skill Name",
        "admin.skills.categoryLabel": "Category",
        "admin.skills.proficiencyLabel": "Proficiency",
        "admin.skills.addButton": "Add Skill",
        "admin.skills.confirmDelete": "Are you sure you want to delete this skill?",
        "admin.skills.empty": "No skills added yet. Start adding your expertise!",
        "admin.skills.category.frontend": "Frontend",
        "admin.skills.category.backend": "Backend",
        "admin.skills.category.devops": "DevOps",
        "admin.skills.category.mobile": "Mobile",
        "admin.skills.category.other": "Other",
        // Admin Testimonials keys
        "admin.testimonials.title": "Testimonials",
        "admin.testimonials.subtitle": "Read and manage feedback from clients and collaborators",
        "admin.testimonials.sectionTitle": "Testimonials",
        "admin.testimonials.addButton": "Add Testimonial",
        "admin.testimonials.editButton": "Edit",
        "admin.testimonials.deleteButton": "Delete",
        "admin.testimonials.confirmDelete": "Are you sure you want to delete this testimonial?",
        "admin.testimonials.empty": "No testimonials yet.",
        "admin.testimonials.emptyDesc": "Client and collaborator feedback will appear here once submitted.",
        "admin.testimonials.ratingLabel": "Rating",
        "admin.testimonials.userLabel": "User",
        "admin.testimonials.status.pending": "Pending",
        "admin.testimonials.status.approved": "Approved",
        "admin.testimonials.status.rejected": "Rejected",
        "admin.testimonials.editTitle": "Edit Testimonial",
        "admin.testimonials.editSaveButton": "Save Changes",
        "admin.testimonials.editCancelButton": "Cancel",
        "admin.testimonials.editSaving": "Saving...",
        // Admin Projects keys
        "admin.projects.title": "Projects",
        "admin.projects.subtitle": "Add, edit, and organize your portfolio projects",
        "admin.projects.cta": "Showcase Your Work • Professional Portfolio",
        "admin.projects.sectionTitle": "Projects",
        "admin.projects.addButton": "Add New Project",
        "admin.projects.cancelButton": "Cancel",
        "admin.projects.addTitle": "Add New Project",
        "admin.projects.addFirstButton": "Add Your First Project",
        "admin.projects.editButton": "Edit",
        "admin.projects.deleteButton": "Delete",
        "admin.projects.confirmDelete": "Are you sure you want to delete this project?",
        "admin.projects.empty": "No Projects Yet",
        "admin.projects.emptyDesc": "Get started by adding your first project to showcase your work and impress potential clients.",
        "admin.projects.form.title": "Project Title *",
        "admin.projects.form.titlePlaceholder": "Enter project title",
        "admin.projects.form.description": "Description *",
        "admin.projects.form.descriptionPlaceholder": "Describe your project and its key features",
        "admin.projects.form.repoUrl": "Repository URL",
        "admin.projects.form.repoUrlPlaceholder": "https://github.com/username/repo",
        "admin.projects.form.liveUrl": "Live Demo URL",
        "admin.projects.form.liveUrlPlaceholder": "https://yourproject.com",
        "admin.projects.form.tags": "Tags *",
        "admin.projects.form.tagsPlaceholder": "React, TypeScript, Next.js (comma-separated)",
        "admin.projects.form.tagsHelp": "Separate tags with commas for better organization",
        "admin.projects.form.creating": "Creating...",
        "admin.projects.form.createButton": "Create Project",
        "admin.projects.editTitle": "Edit Project",
        "admin.projects.editSaveButton": "Update Project",
        "admin.projects.editSaving": "Saving...",
        "admin.projects.editCancelButton": "Cancel",
        "admin.projects.registeredUser": "Registered User",
        "admin.projects.liveDemo": "Live Demo →",
        "admin.projects.repository": "Repository",
        // Admin Hobbies keys
        "admin.hobbies.title": "Hobbies & Interests",
        "admin.hobbies.subtitle": "Share your personality outside of work",
        "admin.hobbies.addTitle": "Add Hobby",
        "admin.hobbies.namePlaceholder": "Hobby Name",
        "admin.hobbies.iconPlaceholder": "Icon (emoji or SVG)",
        "admin.hobbies.addButton": "Add Hobby",
        "admin.hobbies.listTitle": "Hobbies List",
        "admin.hobbies.empty": "No hobbies added yet.",
        "admin.hobbies.deleteButton": "Delete",
        // Admin Experience keys
        "admin.experience.title": "Experience",
        "admin.experience.subtitle": "Showcase your professional journey",
        "admin.experience.addTitle": "Add Experience",
        "admin.experience.positionPlaceholder": "Position",
        "admin.experience.companyPlaceholder": "Company",
        "admin.experience.locationPlaceholder": "Location",
        "admin.experience.startDate": "Start Date",
        "admin.experience.endDate": "End Date",
        "admin.experience.descriptionPlaceholder": "Description (Optional)",
        "admin.experience.addButton": "Add Experience",
        "admin.experience.listTitle": "Experience List",
        "admin.experience.present": "Present",
        "admin.experience.empty": "No experience added yet.",
        "admin.experience.deleteButton": "Delete",
        "nav.home": "Home",
        "nav.projects": "Projects",
        "nav.skills": "Skills",
        "nav.experience": "Experience",
        "nav.education": "Education",
        "nav.hobbies": "Hobbies",
        "nav.cv": "CV",
        "nav.testimonials": "Testimonials",
        "nav.contact": "Contact",
        "hero.greeting": "Welcome!",
        // Homepage keys
        // Admin Dashboard keys
        "admin.dashboard.welcome": "Welcome Back",
        "admin.dashboard.manage": "Manage your portfolio content and view analytics",
        "admin.dashboard.features": "• Real-time Data • Modern Interface",
        "admin.dashboard.totalProjects": "Total Projects",
        "admin.dashboard.totalTestimonials": "Total Testimonials",
        "admin.dashboard.totalMessages": "Total Messages",
        "admin.dashboard.pendingTestimonials": "Pending Testimonials",
        // Admin Education keys
        "admin.education.title": "Education",
        "admin.education.subtitle": "Academic background and certifications",
        "admin.education.addTitle": "Add Education",
        "admin.education.degreePlaceholder": "Degree / Certificate",
        "admin.education.institutionPlaceholder": "Institution",
        "admin.education.startDate": "Start Date",
        "admin.education.endDate": "End Date",
        "admin.education.descriptionPlaceholder": "Description (Optional)",
        "admin.education.addButton": "Add Education",
        "admin.education.present": "Present",
        "admin.education.empty": "No education added yet.",
        "home.name": "Nathan Roos",
        "home.title": "Full Stack Developer & DevOps Developer",
        "home.subtitle": "Crafting scalable applications with cutting-edge technologies.",
        "home.stack": "Next.js • Kubernetes • Modern Cloud Infrastructure",
        "home.exploreProjects": "Explore Projects",
        "home.getInTouch": "Get In Touch",
        "home.projects": "Projects",
        "home.projectsDesc": "Explore cutting-edge applications and technical implementations",
        "home.cv": "CV",
        "home.cvDesc": "Download my latest Curriculum Vitae (CV)",
        "home.testimonials": "Testimonials",
        "home.testimonialsDesc": "Read authentic feedback from clients and collaborators",
        "home.contact": "Contact",
        "home.contactDesc": "Let's collaborate on your next innovative project",
        "home.architecture": "Architecture",
        "home.architectureDesc": "View live cluster topology and infrastructure",
        "home.techArsenal": "Technology Arsenal",
    },
    fr: {
        // Dashboard Site Info keys
        "dashboard.siteinfo.title": "Modifier les infos du site",
        "dashboard.siteinfo.homeTitle": "Titre de la page d'accueil",
        "dashboard.siteinfo.homeTitleHelp": "Ceci est le texte <Full Stack Developer & DevOps Developer/>. Le style restera inchangé.",
        "dashboard.siteinfo.homeStack": "Stack/Technos de la page d'accueil",
        "dashboard.siteinfo.homeStackHelp": "Ceci est le texte de la stack technique (ex : Next.js • Kubernetes • ...). Le style restera inchangé.",
        "dashboard.siteinfo.homeDescription": "Description de la page d'accueil",
        "dashboard.siteinfo.homeDescriptionHelp": "Ceci est le sous-titre sous votre nom. Le style restera inchangé.",
        "dashboard.siteinfo.contactEmail": "Email de contact",
        "dashboard.siteinfo.helpInfo": "Comment puis-je aider",
        "dashboard.siteinfo.directEmail": "Email direct (pour la section Envoyer un message)",
        // Public Projects page keys
        "projects.title": "Projets",
        "projects.intro": "Découvrez mon portfolio d'applications innovantes et de solutions d'infrastructure.",
        "projects.tagline": "Technologies modernes • Architecture évolutive • Prêt pour la production",
        "projects.comingSoon": "Bientôt disponible",
        "projects.empty": "Des projets passionnants sont en cours de développement. Revenez bientôt pour découvrir mes dernières réalisations !",
        // Public Skills page keys
        "skills.title": "Compétences & Expertise",
        "skills.intro": "Un aperçu complet de mes compétences techniques et de mon arsenal professionnel.",
        "skills.empty": "Aucune compétence ajoutée pour le moment.",
        "skills.proficiencyLabel": "Niveau de maîtrise",
        // Public Experience page keys
        "experience.title": "Expérience professionnelle",
        "experience.intro": "Mon parcours professionnel et mes étapes de carrière.",
        "experience.empty": "Aucune expérience ajoutée pour le moment.",
        // Public Education page keys
        "education.title": "Éducation",
        "education.intro": "Parcours académique et certifications.",
        "education.empty": "Aucune formation ajoutée pour le moment.",
        // CV page keys
        // Public Testimonials page keys
        // Public Hobbies page keys
        "hobbies.title": "Loisirs & Centres d'intérêt",
        "hobbies.intro": "Ce que j'aime faire en dehors du code.",
        "hobbies.empty": "Aucun loisir ajouté pour le moment.",
        "hobbies.sectionTitle": "Loisirs",
        "testimonials.title": "Témoignages",
        "testimonials.intro": "Lisez les retours authentiques de clients et collaborateurs.",
        "testimonials.empty": "Aucun témoignage pour le moment.",
        "testimonials.button": "Ajouter un témoignage",
        "testimonials.loading": "Chargement des témoignages...",
        "testimonials.error": "Échec du chargement des témoignages.",
        "testimonials.rating": "Note",
        "testimonials.date": "Date",
        "testimonials.author": "Auteur",
        "cv.title": "CV",
        "cv.intro": "Téléchargez ou consultez mon dernier CV ci-dessous.",
        "cv.button": "Voir / Télécharger le CV",
        "cv.preview": "Aperçu du CV",
        // Contact page keys
        "contact.title": "Contact",
        "contact.intro": "Vous avez un projet en tête ? Discutons de la façon dont nous pouvons travailler ensemble pour concrétiser vos idées.",
        "contact.collabTagline": "Collaboration • Innovation • Résultats",
        "contact.connectTitle": "Entrons en contact",
        "contact.emailTitle": "Email",
        "contact.locationTitle": "Localisation",
        "contact.locationDesc": "Disponible pour le travail à distance dans le monde entier",
        "contact.responseTitle": "Délai de réponse",
        "contact.responseDesc": "Généralement sous 24 heures",
        "contact.helpTitle": "Ce que je peux apporter",
        "contact.helpWeb": "Développement d'applications web full-stack",
        "contact.helpCloud": "Mise en place et optimisation d'infrastructures cloud",
        "contact.helpK8s": "Déploiement Kubernetes et conseil DevOps",
        "contact.helpArch": "Architecture technique et conception de systèmes",
        // Admin Messages keys
        "admin.messages.title": "Messages",
        "admin.messages.subtitle": "Consultez et gérez les messages du formulaire de contact",
        "admin.messages.cta": "Restez connecté avec votre audience",
        "admin.messages.sectionTitle": "Boîte de réception",
        "admin.messages.deleteButton": "Supprimer",
        "admin.messages.confirmDelete": "Êtes-vous sûr de vouloir supprimer ce message ?",
        "admin.messages.empty": "Aucun message pour le moment.",
        "admin.messages.emptyDesc": "Les messages soumis via votre formulaire de contact apparaîtront ici.",
        "admin.messages.registeredUser": "Utilisateur enregistré",
        "admin.messages.loading": "Chargement des messages...",
        "admin.messages.error": "Échec du chargement des messages.",
        "admin.messages.email": "Email",
        "admin.messages.name": "Nom",
        "admin.messages.date": "Date",
        "admin.messages.message": "Message",
        // Admin Skills keys
        "admin.skills.title": "Compétences",
        "admin.skills.subtitle": "Ajoutez, modifiez et organisez vos compétences techniques",
        "admin.skills.addTitle": "Ajouter une compétence",
        "admin.skills.nameLabel": "Nom de la compétence",
        "admin.skills.categoryLabel": "Catégorie",
        "admin.skills.proficiencyLabel": "Niveau de maîtrise",
        "admin.skills.addButton": "Ajouter la compétence",
        "admin.skills.confirmDelete": "Êtes-vous sûr de vouloir supprimer cette compétence ?",
        "admin.skills.empty": "Aucune compétence pour le moment. Commencez à ajouter votre expertise !",
        "admin.skills.category.frontend": "Frontend",
        "admin.skills.category.backend": "Backend",
        "admin.skills.category.devops": "DevOps",
        "admin.skills.category.mobile": "Mobile",
        "admin.skills.category.other": "Autre",
        // Admin Testimonials keys
        "admin.testimonials.title": "Témoignages",
        "admin.testimonials.subtitle": "Lisez et gérez les retours des clients et collaborateurs",
        "admin.testimonials.sectionTitle": "Témoignages",
        "admin.testimonials.addButton": "Ajouter un témoignage",
        "admin.testimonials.editButton": "Modifier",
        "admin.testimonials.deleteButton": "Supprimer",
        "admin.testimonials.confirmDelete": "Êtes-vous sûr de vouloir supprimer ce témoignage ?",
        "admin.testimonials.empty": "Aucun témoignage pour le moment.",
        "admin.testimonials.emptyDesc": "Les retours des clients et collaborateurs apparaîtront ici une fois soumis.",
        "admin.testimonials.ratingLabel": "Note",
        "admin.testimonials.userLabel": "Utilisateur",
        "admin.testimonials.status.pending": "En attente",
        "admin.testimonials.status.approved": "Approuvé",
        "admin.testimonials.status.rejected": "Rejeté",
        "admin.testimonials.editTitle": "Modifier le témoignage",
        "admin.testimonials.editSaveButton": "Enregistrer les modifications",
        "admin.testimonials.editCancelButton": "Annuler",
        "admin.testimonials.editSaving": "Enregistrement...",
        // Admin Projects keys
        "admin.projects.title": "Projets",
        "admin.projects.subtitle": "Ajoutez, modifiez et organisez vos projets de portfolio",
        "admin.projects.cta": "Mettez en valeur votre travail • Portfolio professionnel",
        "admin.projects.sectionTitle": "Projets",
        "admin.projects.addButton": "Ajouter un projet",
        "admin.projects.cancelButton": "Annuler",
        "admin.projects.addTitle": "Ajouter un projet",
        "admin.projects.addFirstButton": "Ajoutez votre premier projet",
        "admin.projects.editButton": "Modifier",
        "admin.projects.deleteButton": "Supprimer",
        "admin.projects.confirmDelete": "Êtes-vous sûr de vouloir supprimer ce projet ?",
        "admin.projects.empty": "Aucun projet pour le moment",
        "admin.projects.emptyDesc": "Commencez par ajouter votre premier projet pour mettre en valeur votre travail et impressionner les clients potentiels.",
        "admin.projects.form.title": "Titre du projet *",
        "admin.projects.form.titlePlaceholder": "Entrez le titre du projet",
        "admin.projects.form.description": "Description *",
        "admin.projects.form.descriptionPlaceholder": "Décrivez votre projet et ses principales fonctionnalités",
        "admin.projects.form.repoUrl": "URL du dépôt",
        "admin.projects.form.repoUrlPlaceholder": "https://github.com/utilisateur/repo",
        "admin.projects.form.liveUrl": "URL de la démo",
        "admin.projects.form.liveUrlPlaceholder": "https://votreprojet.com",
        "admin.projects.form.tags": "Tags *",
        "admin.projects.form.tagsPlaceholder": "React, TypeScript, Next.js (séparés par des virgules)",
        "admin.projects.form.tagsHelp": "Séparez les tags par des virgules pour une meilleure organisation",
        "admin.projects.form.creating": "Création...",
        "admin.projects.form.createButton": "Créer le projet",
        "admin.projects.editTitle": "Modifier le projet",
        "admin.projects.editSaveButton": "Mettre à jour le projet",
        "admin.projects.editSaving": "Enregistrement...",
        "admin.projects.editCancelButton": "Annuler",
        "admin.projects.registeredUser": "Utilisateur enregistré",
        "admin.projects.liveDemo": "Démo en ligne →",
        "admin.projects.repository": "Dépôt",
        // Admin Hobbies keys
        // Admin Projects keys
        // Admin Projects keys (see below for French)

        // Admin Testimonials keys
        // Admin Testimonials keys (see below for French)

        // Admin Skills keys
        // Admin Skills keys (see below for French)

        // Admin Messages keys
        // Admin Messages keys (see below for French)
        "admin.hobbies.title": "Loisirs & Centres d'intérêt",
        "admin.hobbies.subtitle": "Partagez votre personnalité en dehors du travail",
        "admin.hobbies.addTitle": "Ajouter un loisir",
        // Admin Projects keys
        // Admin Projects keys (see above for English)

        // Admin Testimonials keys
        // Admin Testimonials keys (see above for English)

        // Admin Skills keys
        // Admin Skills keys (see above for English)

        // Admin Messages keys
        // Admin Messages keys (see above for English)
        // Admin Dashboard Quick Actions
        "admin.dashboard.quickActions": "Actions rapides",
        "admin.dashboard.viewProjects": "Voir les projets",
        "admin.dashboard.manageProjects": "Gérez vos projets de portfolio",
        "admin.hobbies.namePlaceholder": "Nom du loisir",
        "admin.hobbies.iconPlaceholder": "Icône (emoji ou SVG)",
        "admin.hobbies.addButton": "Ajouter",
        "admin.hobbies.listTitle": "Liste des loisirs",
        "admin.hobbies.empty": "Aucun loisir ajouté pour le moment.",
        "admin.hobbies.deleteButton": "Supprimer",
        // Admin Experience keys
        "admin.experience.title": "Expérience",
        "admin.experience.subtitle": "Mettez en valeur votre parcours professionnel",
        "admin.experience.addTitle": "Ajouter une expérience",
        "admin.experience.positionPlaceholder": "Poste",
        "admin.experience.companyPlaceholder": "Entreprise",
        "admin.experience.locationPlaceholder": "Lieu",
        "admin.experience.startDate": "Date de début",
        "admin.experience.endDate": "Date de fin",
        "admin.experience.descriptionPlaceholder": "Description (optionnelle)",
        "admin.experience.addButton": "Ajouter",
        "admin.experience.listTitle": "Liste des expériences",
        "admin.experience.present": "En cours",
        "admin.experience.empty": "Aucune expérience ajoutée pour le moment.",
        "admin.experience.deleteButton": "Supprimer",
            "admin.experience.editTitle": "Modifier l'expérience",
            "admin.experience.editSaveButton": "Enregistrer les modifications",
            "admin.experience.editCancelButton": "Annuler",
            "admin.experience.editButton": "Modifier",
        "nav.home": "Accueil",
        "nav.projects": "Projets",
        "nav.skills": "Compétences",
        "nav.experience": "Expérience",
        "nav.education": "Éducation",
        "nav.hobbies": "Loisirs",
        "nav.cv": "CV",
        "nav.testimonials": "Témoignages",
        "nav.contact": "Contact",
        "hero.greeting": "Bienvenue!",
        // Homepage keys
        // Admin Dashboard keys
        "admin.dashboard.welcome": "Bon retour !",
        "admin.dashboard.manage": "Gérez le contenu de votre portfolio et consultez les analyses",
        "admin.dashboard.features": "• Données en temps réel • Interface moderne",
        "admin.dashboard.totalProjects": "Projets totaux",
        "admin.dashboard.totalTestimonials": "Témoignages totaux",
        "admin.dashboard.totalMessages": "Messages totaux",
        "admin.dashboard.pendingTestimonials": "Témoignages en attente",
        // Admin Education keys
        "admin.education.title": "Éducation",
        "admin.education.subtitle": "Parcours académique et certifications",
        "admin.education.addTitle": "Ajouter une formation",
        "admin.education.degreePlaceholder": "Diplôme / Certificat",
        "admin.education.institutionPlaceholder": "Établissement",
        "admin.education.startDate": "Date de début",
        "admin.education.endDate": "Date de fin",
        "admin.education.descriptionPlaceholder": "Description (optionnelle)",
        "admin.education.addButton": "Ajouter",
        "admin.education.present": "En cours",
        "admin.education.empty": "Aucune formation ajoutée pour le moment.",
        "home.name": "Nathan Roos",
        "home.title": "Développeur Full Stack & DevOps",
        "home.subtitle": "Créer des applications évolutives avec des technologies de pointe.",
        "home.stack": "Next.js • Kubernetes • Infrastructure Cloud Moderne",
        "home.exploreProjects": "Voir les Projets",
        "home.getInTouch": "Contactez-moi",
        "home.projects": "Projets",
        "home.projectsDesc": "Découvrez des applications innovantes et des implémentations techniques",
        "home.cv": "CV",
        "home.cvDesc": "Téléchargez mon dernier Curriculum Vitae (CV)",
        "home.testimonials": "Témoignages",
        "home.testimonialsDesc": "Lisez les retours authentiques de clients et collaborateurs",
        "home.contact": "Contact",
        "home.contactDesc": "Collaborons sur votre prochain projet innovant",
        "home.architecture": "Architecture",
        "home.architectureDesc": "Voir la topologie du cluster et l'infrastructure en direct",
        "home.techArsenal": "Arsenal Technologique",
    }
};

// 3. Create the Context
interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// 4. Create the Provider Component
export function LanguageProvider({ children }: { children: ReactNode }) {
    const [language, setLanguage] = useState<Language>("en");
    // The magic translation function
    const t = (key: string) => {
        return translations[language][key as keyof typeof translations["en"]] || key;
    };
    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

// 5. Create a custom hook for easy usage
export function useLanguage() {
    const context = useContext(LanguageContext);
    if (!context) throw new Error("useLanguage must be used within a LanguageProvider");
    return context;
}
